/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
//#include <stdio.h>

//RCC Clock register(RCC AHB1)
uint32_t* volatile pRccahb1 = (uint32_t*)0x40023830;
//
uint32_t* volatile pGpio_modereg = (uint32_t*) 0x40020C00;
uint32_t* volatile pGpio_data_reg = (uint32_t*) 0x40020C14;

void led_init();
void led_on(uint8_t pin);
void led_off(uint8_t pin);
void delay(uint32_t sec);

int main(void)
{
	led_init();
	while(1)
	{
			led_on(12);
			led_on(13);
			led_on(14);
			led_on(15);
			delay(160000);
			led_off(12);
			led_off(13);
			led_off(14);
			led_off(15);
			delay(160000);
	}




}


void led_init(){

	//Enables the clock bus for GPIOD
	*pRccahb1 |= (1<<3);

	//Clears the value of 24,25,26,27 bits on Gpio_Mode_reg.
	*pGpio_modereg &= ~(15<<24);
	//Clears the value of 28,29,30,31 bits on Gpio_Mode_reg.
	*pGpio_modereg &= ~(15<<28);

	//Set the 12,13,14,15 pin on GPIOD as a General purpose of output mode.
	for(int i=24; i<=30;i++,i++)
	{
		*pGpio_modereg |= (1<<i);
	}

}

void led_on(uint8_t pin)
{

	*pGpio_data_reg |= (1<<pin);
}

void led_off(uint8_t pin){

	*pGpio_data_reg &= ~(1<<pin);
}
void delay(uint32_t sec){
	for(int i=0;i<sec;i++){

	}

}
